### ISSUE TITLE
Fails to place trades on lamassu-server@0.2.5

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-coinbase#4]
When attempting to place a trade on `lamassu-server@0.2.5`, the Coinbase module presents the error:

```
[2015-04-12T00:04:45.256Z] DEBUG: lamassu-server/10425 on lamassu-coinbase10: making a trade: 0.0084

/usr/local/lib/node_modules/lamassu-server/node_modules/wreck/lib/index.js:375
    return this._shortcutWrap('POST', uri, options, callback);
                ^
TypeError: Object #<Object> has no method '_shortcutWrap'
    at internals.Client.post (/usr/local/lib/node_modules/lamassu-server/node_modules/wreck/lib/index.js:375:17)
    at Object.authRequest (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-coinbase/lib/common.js:45:3)
    at trade (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-coinbase/lib/trader.js:65:10)
    at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-coinbase/lib/trader.js:34:5
    at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-coinbase/lib/trader.js:20:5
    at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-coinbase/lib/ticker.js:35:5
    at /usr/local/lib/node_modules/lamassu-server/node_modules/wreck/lib/index.js:417:20
    at finish (/usr/local/lib/node_modules/lamassu-server/node_modules/wreck/lib/index.js:276:16)
    at wrapped (/usr/local/lib/node_modules/lamassu-server/node_modules/wreck/node_modules/hoek/lib/index.js:818:20)
    at onReaderFinish (/usr/local/lib/node_modules/lamassu-server/node_modules/wreck/lib/index.js:310:16)
[2015-04-12T00:04:45.584Z]  INFO: lamassu-server/10443 on lamassu-coinbase10: Version: 2.2.5
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
lamassu-server listening on port 3000 (https)
[2015-04-12T00:04:45.735Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: plugin(ticker) loaded: Coinbase
[2015-04-12T00:04:45.755Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: plugin(transfer) loaded: Blockchain
[2015-04-12T00:04:45.760Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: plugin(trade) loaded: Coinbase
[2015-04-12T00:04:45.761Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: checking for trades
[2015-04-12T00:04:45.762Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: consolidated:  {"currency":"USD","satoshis":0}
[2015-04-12T00:04:45.762Z] DEBUG: lamassu-server/10443 on lamassu-coinbase10: rejecting 0 trade
```

Versions of `wreck`:

```
root@lamassu-coinbase10:~# npm -g ls wreck
/usr/local/lib
└─┬ lamassu-server@2.2.5
  ├─┬ lamassu-bitcoinaverage@1.0.3
  │ └── wreck@3.0.0 
  ├─┬ lamassu-bitpay@1.0.3
  │ └── wreck@3.0.0 
  ├─┬ lamassu-bitstamp@1.0.2
  │ └── wreck@3.0.0 
  ├─┬ lamassu-blockchain@1.1.3
  │ └── wreck@3.0.0 
  ├─┬ lamassu-blockcypher@0.1.0
  │ └── wreck@3.0.0 
  ├─┬ lamassu-coindesk@1.0.3
  │ └── wreck@3.0.0 
  ├─┬ lamassu-identitymind@1.2.7
  │ └── wreck@3.0.0 
  └── wreck@5.4.0 
```

I then fixed lamassu-server to using `wreck@3.0.0`, though the server did not attempt to place the trade:

```
[2015-04-12T00:14:40.533Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: rejecting 0 trade
[2015-04-12T00:14:44.415Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: poll request from: 3A:7F:96:4F:BD:BA:4B:BC:EA:66:FB:D8:9F:1C:66:F6:D5:63:93:08
[2015-04-12T00:14:45.539Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: checking for trades
[2015-04-12T00:14:45.544Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: consolidated:  {"currency":"USD","satoshis":421000}
[2015-04-12T00:14:45.545Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: making a trade: 0.00421
[2015-04-12T00:14:50.034Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: poll request from: 3A:7F:96:4F:BD:BA:4B:BC:EA:66:FB:D8:9F:1C:66:F6:D5:63:93:08
[2015-04-12T00:14:50.564Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: checking for trades
[2015-04-12T00:14:50.564Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: consolidated:  {"currency":"USD","satoshis":842000}
[2015-04-12T00:14:50.565Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: making a trade: 0.00842
[2015-04-12T00:14:54.512Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: poll request from: 3A:7F:96:4F:BD:BA:4B:BC:EA:66:FB:D8:9F:1C:66:F6:D5:63:93:08
[2015-04-12T00:14:55.578Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: checking for trades
[2015-04-12T00:14:55.579Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: consolidated:  {"currency":"USD","satoshis":842000}
[2015-04-12T00:14:55.579Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: making a trade: 0.00842
[2015-04-12T00:15:00.103Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: poll request from: 3A:7F:96:4F:BD:BA:4B:BC:EA:66:FB:D8:9F:1C:66:F6:D5:63:93:08
[2015-04-12T00:15:00.594Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: checking for trades
[2015-04-12T00:15:00.594Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: consolidated:  {"currency":"USD","satoshis":842000}
[2015-04-12T00:15:00.594Z] DEBUG: lamassu-server/11163 on lamassu-coinbase10: making a trade: 0.00842
```

**Comment by naconner** [comment]
Resolved by fixing lamassu-server's wreck version to 5.1.0 instead of the latest 5.4.0.

https://github.com/lamassu/lamassu-server/pull/57

@joshmh
